### ISSUE TITLE
Should it be Static?

### ISSUE THREAD

**Issue by StanLindsey** [southamptondigital/southamptondigital.github.io#1]
Firstly, I'm not attached to the current implementation. So happy for it to go either way. I just wanted to throw something together as a base because the core idea is good! 

Lots of JS. Maybe it should just be static Jekyll and people submit pull requests to add events. 

Arguments for Static: 
- No JS down the wire
- Will load faster
- Who doesn't know Git in 2017?
- Will work on older browsers
- Read motherfuckingwebsite.com

Arguments for JS/Vue:
- Omgosh it is a totally RealTime Application! (Super Important for the 100s of events to be added every second)
- I wanted an excuse to use Vue =P
- Nobody has to deal with pull requests for events, but we would have to do auth/validation. 
- Add new features like comments or profiles and mini-sites and PWA and lasers. 
- As soon as you add 1 Image to the site, it'll be bigger than all the JS in use.
- Currently there is no build system for minifying or unrolling etc

Discuss!

**Comment by adamtomat** [comment]
> Add new features like comments or profiles and mini-sites and PWA and lasers.

You could do these on a static site too 🙃

**Comment by StanLindsey** [comment]
True. And all that isn't a necessary. 

My main issue with purely static was keeping it updated as any date info would only be ran on build. So past events would stick around unless the repo is committed on.

So it was either a simple server or something client based for Github Pages. Yes, Vue is overkill and there is extra includes that I couldn't be bothered to write myself for the sake of a prototype.

If Client side is needed, this can all be done in plain JS, pulling from Firebase & adding dom elements. 

Oh actually, a bot that just commits an empty commit daily would do it if we're desperate for pure static. =D

**Comment by benjie** [comment]
I'm voting static; any "time ago" stuff can be added in client-side JS based on data-timestamp attributes or similar. We'd also be able to easily generate RSS, iCal, etc feeds this way. We can then hook up to twitter/slack/etc via a bot if people don't find posting via GitHub convenient.

**Comment by StanLindsey** [comment]
Consensus achieved!

**Comment by StanLindsey** [comment]
I've pushed a Jekyll version of the same site. Used a Jekyll collection for the events so people can just commit a self-contained file for each event. Also invited the Rareloop guys as team members.
